version: "3.4"
services:
  php:
    volumes:
      - "./src:/var/www/site"
      - "./docker/php/.user.ini:/usr/local/etc/php/php.ini"
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: 1000:1000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: proof-registry-db
      DB_USERNAME: db-user
      DB_PASSWORD: secret
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/site
    ports:
      - 8080:80
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: proof-registry-db
      MYSQL_USER: db-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - 3306:3306
    volumes:
      - "db-data:/var/lib/mysql/data"
volumes:
  db-data: {}
