version: "3.4"
services:
  php:
    volumes:
      - "./src:/var/www/site"
      - "./docker/php/.user.ini:/usr/local/etc/php/php.ini"
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: 1000:1000
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/site
    ports:
      - 8080:80
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - "db-data:/var/lib/mysql/data"
volumes:
  db-data: {}
